#!/bin/sh

mkdir -p ~/.local/bin
curl -s https://raw.githubusercontent.com/alexsch01/distbox/wayland/distbox > ~/.local/bin/distbox
chmod +x ~/.local/bin/distbox
echo "$HOME/.local/bin needs to be in the PATH variable"
